### signup user(zhangsan)

POST http://localhost:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "zhangsan",
  "email": "zhangsan@qq.com",
  "password": "zhangsan1104"
}

### signup user(lisi)

POST http://localhost:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "lisi",
  "email": "lisi@qq.com",
  "password": "lisi1104"
}

### signup user(wangwu)

POST http://localhost:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "wangwu",
  "email": "wangwu@qq.com",
  "password": "wangwu1104"
}


### signin user

# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
  "email": "zhangsan@qq.com",
  "password": "zhangsan1104"
}

@token = {{signin.response.body.token}}

### signin user (invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
  "email": "zhangsan@163.com",
  "password": "zhangsan1104"
}

### get user list to workspace
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### get chat list

GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}


### create chat
POST http://localhost:6688/api/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "members": [1,2]
}


### update chat

PATCH http://localhost:6688/api/chat/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "members": [1,2,3]
}

### delete chat

DELETE http://localhost:6688/api/chat/1
Authorization: Bearer {{token}}

### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="2020122718461226960.jpg"
Content-Type: application/octet-stream

< e:\Users\ASUS\Desktop\pic\2020122718461226960.jpg
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello World!
--MyBoundary--

### get file

GET http://localhost:6688/api/files/1/1e2/078/862bd199a443a09348c11e463c80527905.jpg
Authorization: Bearer {{token}}


### send a message
POST http://localhost:6688/api/chat/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "hello, world!"
}

### get messages list

GET http://localhost:6688/api/chat/1/message?limit=6
Authorization: Bearer {{token}}


### delete message

DELETE http://localhost:6688/api/chat/1/message?message_id=10
Authorization: Bearer {{token}}
