server:
  port: 6688
  db_url: postgres://postgres:nyh196511@localhost:5432/chat
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEINarVLdgxSAuMozJ3iZ+ZOGwk6bAVCGbrRN9NfNJfRpN
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAmfKzAsmhiQ8ghI+N3nxVxdjXCbx/ettQBr669e+ttCo=
    -----END PUBLIC KEY-----
